baseURL = 'https://ashinto.sh/'
languageCode = 'en-us'
title = 'ashinto.sh'

[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 10

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

# You can configure external links to open in new tabs by adding this parameter
openLinksInNewTab = true

displayDateFormat = "2006-01-02"

# Global metadata display settings
# Each can be overridden in individual post frontmatter
showMetadata = true       # Master switch for all metadata display
showPublishedDate = true  # Show published date on post page
showReadingTime = true    # Show reading time on post page
showTags = true           # Show tags on post page
showAuthors = true        # Show authors on post page
showCategories = true     # Show categories on post page

[params]
user = "ash"
hostname = "ashinto.sh"

  [params.styles]
  color = "#13b27a"

  [params.author]
    name = "ashinto.sh"  # Website and RSS feed author
    email = "ash@ashinto.sh"  # RSS feed email address

  [[params.social]]
  key = 0
  name = "github"
  url = "https://github.com/Ashintosh"
  target = "_blank"
  aria = "GitHub Profile"

  [[params.social]]
  key = 1
  name = "tryhackme"
  url = "https://tryhackme.com/p/4shintosh"
  aria = "TryHackMe Profile"

  # [[params.social]]
  # key = 2
  # name = "linkedin"
  # url = "https://www.example.com"
  # aria = "LinkedIn Profile"

  [[params.social]]
  key = 3
  name = "email"
  url = "mailto:ash@ashinto.sh"
  aria = "My e-Mail Address"
